language: java

jdk:
  - oraclejdk8

before_install:
  - openssl aes-256-cbc -K $encrypted_d0084058d1d5_key -iv $encrypted_d0084058d1d5_iv -in jcb-histoire.enc -out jcb-histoire -d
  - export COMMIT_MESSAGE=$(git log -1 --pretty=%B)

script:
  - "./gradlew bakeAndPush -Dorg.ajoberstar.grgit.auth.ssh.private=./jcb-histoire"
