language: java
jdk:
- oraclejdk8
before_install:
- openssl aes-256-cbc -K $encrypted_de8b559e04ab_key -iv $encrypted_de8b559e04ab_iv -in jcb-histoire.enc -out jcb-histoire -d
- export COMMIT_MESSAGE=$(git log -1 --pretty=%B)
script:
- "./gradlew bakeAndGitPublish -Dorg.ajoberstar.grgit.auth.ssh.private=./jcb-histoire.ppk"
